/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 13:46:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.ChargeCodesResource;
import org.demo.entity.ChargeCodes;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class ChargeCodesControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final String CHARGEDESCRIPTION = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createChargeCodesTest() {
		// Create an chargeCodes
		ChargeCodes chargeCodes = createMocKChargeCodes(Integer.valueOf(100) , CHARGEDESCRIPTION);
		// Recover this chargeCodes
		ResponseEntity<ChargeCodesResource> result = this.restTemplate.getForEntity("/chargeCodes/1", ChargeCodesResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/chargeCodes/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getChargeDescription()).isEqualTo(CHARGEDESCRIPTION);
		// Try to create the same chargeCodes, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/chargeCodes", chargeCodes, ChargeCodesResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an chargeCodes and assert field
		ChargeCodes chargeCodes = createMocKChargeCodes(Integer.valueOf(100)  , CHARGEDESCRIPTION);
		// Recover this chargeCodes
		ResponseEntity<ChargeCodesResource> result = this.restTemplate.getForEntity("/chargeCodes/1", ChargeCodesResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/chargeCodes/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getChargeDescription()).isEqualTo(CHARGEDESCRIPTION);

		// Change field value

		chargeCodes.setChargeDescription("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<ChargeCodes> request = new RequestEntity<ChargeCodes>(chargeCodes, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/chargeCodes/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the chargeCodes and ensure field are correct
		result = this.restTemplate.getForEntity("/chargeCodes/1", ChargeCodesResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/chargeCodes/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getChargeDescription()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<ChargeCodes> request = new RequestEntity<ChargeCodes>(new ChargeCodes(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/chargeCodes/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an chargeCodes
		createMocKChargeCodes(Integer.valueOf(100)  , CHARGEDESCRIPTION);
		// Recover this chargeCodes and test if all is ok
		ResponseEntity<ChargeCodesResource> result = this.restTemplate.getForEntity("/chargeCodes/1", ChargeCodesResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the chargeCodes
		RequestEntity<ChargeCodes> request = new RequestEntity<ChargeCodes>(new ChargeCodes(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/chargeCodes/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the chargeCodes and ensure it's don't exist
		// Recover this chargeCodes and test if all is ok
		result = this.restTemplate.getForEntity("/chargeCodes/1", ChargeCodesResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the chargeCodes
		RequestEntity<ChargeCodes> request = new RequestEntity<ChargeCodes>(new ChargeCodes(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/chargeCodes/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getChargeCodessTest() {
		// First call assert no element
		ResponseEntity<PagedResources<ChargeCodesResource>> result = this.search("/chargeCodes");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<ChargeCodesResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 chargeCodes
		for (int i = 1; i < 22; i++) {
			createMocKChargeCodes(new Integer((int)i),String.valueOf(i));
		}
		result = this.search("/chargeCodes");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/chargeCodes?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getChargeCodessTestFilter() {
		// Create an chargeCodes
		ChargeCodes chargeCodes = createMocKChargeCodes(Integer.valueOf(100) , CHARGEDESCRIPTION);
		RequestEntity<ChargeCodes> request = null;
		ResponseEntity<PagedResources<ChargeCodesResource>> result = null;
		PagedResources<ChargeCodesResource> page = null;
		// Test chargeDescription filter
		// Set the value on entity and update
		chargeCodes.setChargeDescription("c");
		// Process update
		request = new RequestEntity<ChargeCodes>(chargeCodes, HttpMethod.PUT, null);
		this.restTemplate.exchange("/chargeCodes/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test chargeDescription filter
		result = this.search("/chargeCodes?size=20&chargeDescription=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (ChargeCodesResource chargeCodesResource : page.getContent()) {
			assertThat(chargeCodesResource.getChargeDescription()).startsWith("c");
		}
	}

	private ChargeCodes createMocKChargeCodes(Integer chargeCode, String chargeDescription) {
		ChargeCodes chargeCodesMock = new ChargeCodes();
		chargeCodesMock.setChargeCode(chargeCode);
		chargeCodesMock.setChargeDescription(chargeDescription);
		this.restTemplate.postForLocation("/chargeCodes", chargeCodesMock);
		return chargeCodesMock;
	}

	private ResponseEntity<PagedResources<ChargeCodesResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<ChargeCodesResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<ChargeCodesResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}