/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 13:46:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.ProblemsResource;
import org.demo.entity.Problems;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class ProblemsControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final String PROBLEMDESCRIPTION = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createProblemsTest() {
		// Create an problems
		Problems problems = createMocKProblems(Integer.valueOf(100) , PROBLEMDESCRIPTION);
		// Recover this problems
		ResponseEntity<ProblemsResource> result = this.restTemplate.getForEntity("/problems/1", ProblemsResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/problems/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getProblemDescription()).isEqualTo(PROBLEMDESCRIPTION);
		// Try to create the same problems, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/problems", problems, ProblemsResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an problems and assert field
		Problems problems = createMocKProblems(Integer.valueOf(100)  , PROBLEMDESCRIPTION);
		// Recover this problems
		ResponseEntity<ProblemsResource> result = this.restTemplate.getForEntity("/problems/1", ProblemsResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/problems/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getProblemDescription()).isEqualTo(PROBLEMDESCRIPTION);

		// Change field value

		problems.setProblemDescription("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<Problems> request = new RequestEntity<Problems>(problems, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/problems/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the problems and ensure field are correct
		result = this.restTemplate.getForEntity("/problems/1", ProblemsResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/problems/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getProblemDescription()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<Problems> request = new RequestEntity<Problems>(new Problems(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/problems/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an problems
		createMocKProblems(Integer.valueOf(100)  , PROBLEMDESCRIPTION);
		// Recover this problems and test if all is ok
		ResponseEntity<ProblemsResource> result = this.restTemplate.getForEntity("/problems/1", ProblemsResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the problems
		RequestEntity<Problems> request = new RequestEntity<Problems>(new Problems(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/problems/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the problems and ensure it's don't exist
		// Recover this problems and test if all is ok
		result = this.restTemplate.getForEntity("/problems/1", ProblemsResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the problems
		RequestEntity<Problems> request = new RequestEntity<Problems>(new Problems(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/problems/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getProblemssTest() {
		// First call assert no element
		ResponseEntity<PagedResources<ProblemsResource>> result = this.search("/problems");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<ProblemsResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 problems
		for (int i = 1; i < 22; i++) {
			createMocKProblems(new Integer((int)i),String.valueOf(i));
		}
		result = this.search("/problems");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/problems?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getProblemssTestFilter() {
		// Create an problems
		Problems problems = createMocKProblems(Integer.valueOf(100) , PROBLEMDESCRIPTION);
		RequestEntity<Problems> request = null;
		ResponseEntity<PagedResources<ProblemsResource>> result = null;
		PagedResources<ProblemsResource> page = null;
		// Test problemDescription filter
		// Set the value on entity and update
		problems.setProblemDescription("c");
		// Process update
		request = new RequestEntity<Problems>(problems, HttpMethod.PUT, null);
		this.restTemplate.exchange("/problems/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test problemDescription filter
		result = this.search("/problems?size=20&problemDescription=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (ProblemsResource problemsResource : page.getContent()) {
			assertThat(problemsResource.getProblemDescription()).startsWith("c");
		}
	}

	private Problems createMocKProblems(Integer problemCode, String problemDescription) {
		Problems problemsMock = new Problems();
		problemsMock.setProblemCode(problemCode);
		problemsMock.setProblemDescription(problemDescription);
		this.restTemplate.postForLocation("/problems", problemsMock);
		return problemsMock;
	}

	private ResponseEntity<PagedResources<ProblemsResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<ProblemsResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<ProblemsResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}