/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 13:46:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.StatusCodeResource;
import org.demo.entity.StatusCode;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class StatusCodeControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final String STATUSDECRIPTION = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createStatusCodeTest() {
		// Create an statusCode
		StatusCode statusCode = createMocKStatusCode(Integer.valueOf(100) , STATUSDECRIPTION);
		// Recover this statusCode
		ResponseEntity<StatusCodeResource> result = this.restTemplate.getForEntity("/statusCode/1", StatusCodeResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/statusCode/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getStatusDecription()).isEqualTo(STATUSDECRIPTION);
		// Try to create the same statusCode, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/statusCode", statusCode, StatusCodeResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an statusCode and assert field
		StatusCode statusCode = createMocKStatusCode(Integer.valueOf(100)  , STATUSDECRIPTION);
		// Recover this statusCode
		ResponseEntity<StatusCodeResource> result = this.restTemplate.getForEntity("/statusCode/1", StatusCodeResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/statusCode/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getStatusDecription()).isEqualTo(STATUSDECRIPTION);

		// Change field value

		statusCode.setStatusDecription("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<StatusCode> request = new RequestEntity<StatusCode>(statusCode, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/statusCode/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the statusCode and ensure field are correct
		result = this.restTemplate.getForEntity("/statusCode/1", StatusCodeResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/statusCode/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getStatusDecription()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<StatusCode> request = new RequestEntity<StatusCode>(new StatusCode(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/statusCode/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an statusCode
		createMocKStatusCode(Integer.valueOf(100)  , STATUSDECRIPTION);
		// Recover this statusCode and test if all is ok
		ResponseEntity<StatusCodeResource> result = this.restTemplate.getForEntity("/statusCode/1", StatusCodeResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the statusCode
		RequestEntity<StatusCode> request = new RequestEntity<StatusCode>(new StatusCode(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/statusCode/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the statusCode and ensure it's don't exist
		// Recover this statusCode and test if all is ok
		result = this.restTemplate.getForEntity("/statusCode/1", StatusCodeResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the statusCode
		RequestEntity<StatusCode> request = new RequestEntity<StatusCode>(new StatusCode(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/statusCode/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getStatusCodesTest() {
		// First call assert no element
		ResponseEntity<PagedResources<StatusCodeResource>> result = this.search("/statusCode");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<StatusCodeResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 statusCode
		for (int i = 1; i < 22; i++) {
			createMocKStatusCode(new Integer((int)i),String.valueOf(i));
		}
		result = this.search("/statusCode");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/statusCode?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getStatusCodesTestFilter() {
		// Create an statusCode
		StatusCode statusCode = createMocKStatusCode(Integer.valueOf(100) , STATUSDECRIPTION);
		RequestEntity<StatusCode> request = null;
		ResponseEntity<PagedResources<StatusCodeResource>> result = null;
		PagedResources<StatusCodeResource> page = null;
		// Test statusDecription filter
		// Set the value on entity and update
		statusCode.setStatusDecription("c");
		// Process update
		request = new RequestEntity<StatusCode>(statusCode, HttpMethod.PUT, null);
		this.restTemplate.exchange("/statusCode/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test statusDecription filter
		result = this.search("/statusCode?size=20&statusDecription=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (StatusCodeResource statusCodeResource : page.getContent()) {
			assertThat(statusCodeResource.getStatusDecription()).startsWith("c");
		}
	}

	private StatusCode createMocKStatusCode(Integer statusCode, String statusDecription) {
		StatusCode statusCodeMock = new StatusCode();
		statusCodeMock.setStatusCode(statusCode);
		statusCodeMock.setStatusDecription(statusDecription);
		this.restTemplate.postForLocation("/statusCode", statusCodeMock);
		return statusCodeMock;
	}

	private ResponseEntity<PagedResources<StatusCodeResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<StatusCodeResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<StatusCodeResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}