/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 13:46:11 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.controller.test;
import static org.assertj.core.api.Assertions.assertThat;

import org.demo.controller.resource.TechniciansResource;
import org.demo.entity.Technicians;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.SpringBootTest.WebEnvironment;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.hateoas.Link;
import org.springframework.hateoas.PagedResources;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.RequestEntity;
import org.springframework.http.ResponseEntity;
import org.springframework.test.context.jdbc.Sql;
import org.springframework.test.context.jdbc.Sql.ExecutionPhase;
import org.springframework.test.context.jdbc.SqlGroup;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;

// Junit specific runner
@RunWith(SpringJUnit4ClassRunner.class)
// Declare as spring boot test and define the port according to properties in
// src/test/resources/application.properties
@SpringBootTest(webEnvironment = WebEnvironment.DEFINED_PORT)
// Ensure all are clean between two method test execution
@SqlGroup({ @Sql(executionPhase = ExecutionPhase.BEFORE_TEST_METHOD, scripts = "classpath:clean.sql") })
public class TechniciansControllerTest {

	@Autowired
	private TestRestTemplate restTemplate;


	private static final String TECHNICIANNAME = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA";

	@Test
	public void createTechniciansTest() {
		// Create an technicians
		Technicians technicians = createMocKTechnicians(Integer.valueOf(100) , TECHNICIANNAME);
		// Recover this technicians
		ResponseEntity<TechniciansResource> result = this.restTemplate.getForEntity("/technicians/1", TechniciansResource.class);
		// The response can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/technicians/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getTechnicianName()).isEqualTo(TECHNICIANNAME);
		// Try to create the same technicians, must return a CONFLICT status code
		result = this.restTemplate.postForEntity("/technicians", technicians, TechniciansResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.CONFLICT);
		// Response body must not be null
		assertThat(result.getBody()).isNull();
	}

	@Test
	public void updateTest() {
		// Create an technicians and assert field
		Technicians technicians = createMocKTechnicians(Integer.valueOf(100)  , TECHNICIANNAME);
		// Recover this technicians
		ResponseEntity<TechniciansResource> result = this.restTemplate.getForEntity("/technicians/1", TechniciansResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		Link link = new Link("http://localhost:9999/technicians/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);
		assertThat(result.getBody().getTechnicianName()).isEqualTo(TECHNICIANNAME);

		// Change field value

		technicians.setTechnicianName("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
		// Process update
		RequestEntity<Technicians> request = new RequestEntity<Technicians>(technicians, HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/technicians/1", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be OK
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Recover the technicians and ensure field are correct
		result = this.restTemplate.getForEntity("/technicians/1", TechniciansResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		assertThat(result.getBody()).isNotNull();
		// Assert the Hateoas self link
		link = new Link("http://localhost:9999/technicians/1", Link.REL_SELF);
		assertThat(result.getBody().getId()).isEqualTo(link);

		assertThat(result.getBody().getTechnicianName()).isEqualTo("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB");
	}

	@Test
	public void updateNotFoundTest() {
		// Process update
		RequestEntity<Technicians> request = new RequestEntity<Technicians>(new Technicians(), HttpMethod.PUT, null);
		ResponseEntity<Void> resultUpdate = this.restTemplate.exchange("/technicians/999", HttpMethod.PUT, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultUpdate).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultUpdate.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteTest() {
		// Create an technicians
		createMocKTechnicians(Integer.valueOf(100)  , TECHNICIANNAME);
		// Recover this technicians and test if all is ok
		ResponseEntity<TechniciansResource> result = this.restTemplate.getForEntity("/technicians/1", TechniciansResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);

		// Delete the technicians
		RequestEntity<Technicians> request = new RequestEntity<Technicians>(new Technicians(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/technicians/1", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_CONTENT
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NO_CONTENT);

		// Try to recover the technicians and ensure it's don't exist
		// Recover this technicians and test if all is ok
		result = this.restTemplate.getForEntity("/technicians/1", TechniciansResource.class);
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void deleteNotFound() {
		// Delete the technicians
		RequestEntity<Technicians> request = new RequestEntity<Technicians>(new Technicians(), HttpMethod.DELETE, null);
		ResponseEntity<Void> resultDelete = this.restTemplate.exchange("/technicians/999", HttpMethod.DELETE, request,
				getTypeRefVoid());
		// The response can't be null
		assertThat(resultDelete).isNotNull();
		// The status code must be NOT_FOUND
		assertThat(resultDelete.getStatusCode()).isEqualTo(HttpStatus.NOT_FOUND);
	}

	@Test
	public void getTechnicianssTest() {
		// First call assert no element
		ResponseEntity<PagedResources<TechniciansResource>> result = this.search("/technicians");
		// The reponse can't be null
		assertThat(result).isNotNull();
		// The status code must be OK
		assertThat(result.getStatusCode()).isEqualTo(HttpStatus.OK);
		// Response body must not be null
		PagedResources<TechniciansResource> page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata()).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(0);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(0);
		// By default page size is 20
		assertThat(page.getMetadata().getSize()).isEqualTo(20);

		// Insert 21 technicians
		for (int i = 1; i < 22; i++) {
			createMocKTechnicians(new Integer((int)i),String.valueOf(i));
		}
		result = this.search("/technicians");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(2);

		// Change the number of element per page and assert the page number
		result = this.search("/technicians?size=3");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(21);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(7);
	}

	@Test
	public void getTechnicianssTestFilter() {
		// Create an technicians
		Technicians technicians = createMocKTechnicians(Integer.valueOf(100) , TECHNICIANNAME);
		RequestEntity<Technicians> request = null;
		ResponseEntity<PagedResources<TechniciansResource>> result = null;
		PagedResources<TechniciansResource> page = null;
		// Test technicianName filter
		// Set the value on entity and update
		technicians.setTechnicianName("c");
		// Process update
		request = new RequestEntity<Technicians>(technicians, HttpMethod.PUT, null);
		this.restTemplate.exchange("/technicians/1", HttpMethod.PUT, request, getTypeRefVoid());
		// Test technicianName filter
		result = this.search("/technicians?size=20&technicianName=c");
		// Response body must not be null
		page = result.getBody();
		assertThat(page).isNotNull();
		assertThat(page.getMetadata().getTotalElements()).isEqualTo(1);
		assertThat(page.getMetadata().getTotalPages()).isEqualTo(1);
		for (TechniciansResource techniciansResource : page.getContent()) {
			assertThat(techniciansResource.getTechnicianName()).startsWith("c");
		}
	}

	private Technicians createMocKTechnicians(Integer technicianId, String technicianName) {
		Technicians techniciansMock = new Technicians();
		techniciansMock.setTechnicianId(technicianId);
		techniciansMock.setTechnicianName(technicianName);
		this.restTemplate.postForLocation("/technicians", techniciansMock);
		return techniciansMock;
	}

	private ResponseEntity<PagedResources<TechniciansResource>> search(String uri) {
		return this.restTemplate.exchange(uri, HttpMethod.GET, null, getTypeRef());
	}

	private ParameterizedTypeReference<PagedResources<TechniciansResource>> getTypeRef() {
		return new ParameterizedTypeReference<PagedResources<TechniciansResource>>() {
		};
	}

	private ParameterizedTypeReference<Void> getTypeRefVoid() {
		return new ParameterizedTypeReference<Void>() {
		};
	}
}