/*
 * Created on 2018-10-01 ( Date ISO 2018-10-01 - Time 16:15:58 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.0.0
*/
package org.demo.service;

import java.util.List;

import javax.transaction.Transactional;

import org.demo.entity.ServiceRequestCalls;
import org.demo.repository.ServiceRequestCallsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
@Transactional
public class ServiceRequestCallsServiceImpl implements ServiceRequestCallsService {

	@Autowired
	private ServiceRequestCallsRepository serviceRequestCallsRepository;

	@Override
	public ServiceRequestCalls getOne(Integer callId) {
		return serviceRequestCallsRepository.findById(callId).get();
	}

	@Override
	public Boolean delete(Integer callId) {
		if (serviceRequestCallsRepository.getOne(callId) != null) {
			serviceRequestCallsRepository.deleteById(callId);
			return true;
		}
		return false;
	}

	@Override
	public ServiceRequestCalls create(ServiceRequestCalls serviceRequestCalls) {
		return serviceRequestCallsRepository.save(serviceRequestCalls);
	}

	@Override
	public ServiceRequestCalls update(ServiceRequestCalls serviceRequestCallsToUpdate) {

		return serviceRequestCallsRepository.save(serviceRequestCallsToUpdate);
	}

	@Override
	public Boolean exist(ServiceRequestCalls serviceRequestCalls) {
		return serviceRequestCallsRepository.existsById(serviceRequestCalls.getCallId());
	}

	@Override
	public List<ServiceRequestCalls> findAll() {
		return serviceRequestCallsRepository.findAll();
	}

}
